spring:
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    properties:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/account_service_database
    username: postgres
    password: bektur97@
    driver-class-name: org.postgresql.Driver
  profiles:
    active=dev
server:
  servlet:
    context-path: /accounts
  port: 8081
